### PR TITLE
Project 1

### PR DESCRIPTION
**Pull request by helman101**
- Used flex to align the page sections
- Used grids to align the infographics photo with 6 text divs
- Grid for articles display in recommendation section
- Used float for aside section picks
- Used absolute positioning to align the editor's picks
- Used position fixed for navbar and "View offers" bar

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

The work you have done looks good :+1: 

However, there are few things changes to make:

- [ ]  Your footer should have a fixed position. It  should stick to the bottom of the screen, just like you did with the header. ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

- [ ] Inside the header tag, use nav tag to wrap the navigation elements,  [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp).

- [ ]  Your pull request comment is not descriptive. It is recommended to provide the details of the features you implemented in a project in your pull request comment. In this project, I would recommend you write down the concepts you implemented in the project.

-  [ ] The links you provided in your readme is not working.

-  [ ] Also, in your README, the image are not coming up.

-  [ ] Remember to complete your README.

#### That is it, when you are done with the changes, submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by iam-Akshat** [comment]
@uche-inyama 
- Do we need to create a new element which is fixed at the bottom, [like this](https://imgur.com/a/oXSfbbh) 
- we checked the links, they are working properly
- the image is also showing on both our computers and in incognito mode too
- we are working on making header semantic.

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested :red_circle: 

### Hello team :wave: 

### Thank you for fixing the header and some other requirements :smile: 

I am sorry my partner couldn't answer you on time, but here's what you need to improve:

- [ ] The fixed footer should be exactly like you mentioned in your screenshot, please implement it.

- [ ] When my partner asked you about the Pull Request comment, he meant the description at the top, your comment was a very nice example of how it is supposed to be. So please, edit your description text explaining what you did in this project with details :+1: 

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by shshamim63 — APPROVED** [review]
## :tada: Status: Approved :partying_face: 
___
Hi @helman101 and @iam-Akshat :wave: 
I just went through your code and those are super organized. PR contains all the info about the tasks that you have covered. Well, the requirements added by the previous reviewer are successfully covered. To the point and clear commit message. Nothing is blocking me from approving this project. This :+1: is from me. You can go ahead and merge it.
___
### :clubs: Optional Change :clubs: 
- You can make NY Times logo a link.
___
### :four_leaf_clover: Happy Coding :four_leaf_clover: 
___
**Shakhawat Hossain**

**Pull request merged**
